quadrantChart
    title "Reach and engagement of campaigns"
    x-axis "Low Reach" --> "High Reach"
    y-axis "Low Engagement" --> "High Engagement"
    quadrant-1 "We should expand"
    quadrant-2 "Need to promote"
    quadrant-3 "Re-evaluate"
    quadrant-4 "May be improved"
    "2048 Game A": [0.3, 0.6]
    "play2048.co": [0.45, 0.23]
    "2048game.com": [0.57, 0.69]
    "Our Target Product": [0.5, 0.6]